on:
  workflow_call:
    inputs:
      script:
        description: 'Which npm script to run'
        required: false
        type: string
        default: build
      platforms:
        description: 'What platforms to run on'
        required: false
        type: string
        default: '["ubuntu-latest"]'
    secrets:
      CODECOV_TOKEN:
        description: If supplied, send coverage metrics to codecov.io
        required: false
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24, 25]
        platform: ${{ fromJson(inputs.platforms) }}
    runs-on: ${{ matrix.platform }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: true
      - name: Running ${{ inputs.script }} on node ${{ matrix.node-version }}, ${{ matrix.platform }}
        run: npm run ${{ inputs.script }}
      - name: Audit
        run: pnpm audit
      - name: Upload coverage reports to Codecov
        if: env.CODECOV_TOKEN
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

