name: Publish Package to npmjs
on:
  workflow_call:
    inputs:
      docs:
        description: 'Publish docs?'
        required: false
        type: boolean
        default: false
      install:
        description: "Parameters for pnpm run_install, as a JSON string"
        required: false
        type: string
        default: 'true'
      script:
        description: 'Which npm script to run'
        required: false
        type: string
        default: build
jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: ${{ inputs.install }}
      - name: Running ${{ inputs.script }} on node ${{ matrix.node-version }}, ${{ matrix.platform }}
        run: npm run ${{ inputs.script }}
      - run: pnpm audit
      - name: Deploy Docs
        if: inputs.docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
      - run: npm pkg delete devDependencies scripts
      - run: npm publish --access public --provenance
